### ISSUE TITLE
Riffol example: OpenVPN docker container

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/riffol#10]
We want to manage OpenVPN within a docker container.

This involves:

* Riffol needs to take in a configuration that allows configuring OpenVPN (private key, CA public key, CA certificate)
* This configuration can be read in via a Base64-serialized data structure through an environment variable via Docker
* The structure of the serialized configuration should be in NON syntax (i.e. UCL, for now). At this stage, we just need to directly write the configuration files' content without using Nereon to generate them.

e.g. (all this content gets serialized in Base64 to docker which passes it to Riffol)
```hcl
group "openvpn" {
  name = "openvpn"
}

user "openvpn" {
  name = "openvpn"
  group = "${group.openvpn.name}"
}

file "openvpn-main-config" {
  path = "/etc/openvpn/openvpn.conf"
  mode = "0400"
  user = "${user.openvpn.name}"
  group = "${group.openvpn.name}"
  // Full config from https://github.com/OpenVPN/openvpn/blob/master/sample/sample-config-files/server.conf
  content = <<EOF
proto udp
dev tun
dh dh2048.pem
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
keepalive 10 120
tls-auth ta.key 0 # This file is secret
cipher AES-256-CBC
persist-key
persist-tun
status openvpn-status.log
verb 3
explicit-exit-notify 1
EOF
  write_on_start = true
}

file "openvpn-ca-cert" {
  path = "/etc/openvpn/ca.crt"
  mode = "0400"
  user = "${user.openvpn.name}"
  group = "${group.openvpn.name}"
  content = <<EOF
===== BEGIN RSA KEY =====
...
EOF
}

file "openvpn-server-cert" {
  path = "/etc/openvpn/server.crt"
  mode = "0400"
  user = "${user.openvpn.name}"
  group = "${group.openvpn.name}"
  content = <<EOF
===== BEGIN RSA KEY =====
...
EOF
}

file "openvpn-server-key" {
  path = "/etc/openvpn/server.key"
  mode = "0400"
  user = "${user.openvpn.name}"
  group = "${group.openvpn.name}"
  content = <<EOF
===== BEGIN RSA KEY =====
...
EOF
}
```

Once Riffol gets the configuration, it writes the configuration to disk and starts OpenVPN. 

This example should support restarting the OpenVPN process if it dies (without having the main process (Riffol) quit, which will kill the container itself).

So we need to create a repo for this OpenVPN docker container first.

UPDATED: added `mode`, `user` and `group` as well as the definition of user and group.

**Comment by ronaldtse** [comment]
Here it is: https://github.com/riboseinc/riffol-docker-openvpn

**Comment by ronaldtse** [comment]
I've updated the example above to include mode/owner/group.

We should select a `command` or `file` block to achieve this (just one instead of two ways), and `command` is probably better?

```hcl
file "dh" {
  path = "/etc/openvpn/dh.pem"
  mode = "0400"
  user = "${user.openvpn.name}"
  group = "${group.openvpn.name}"
  # no "contents" because content supplied by command.openvpn-dh-key
}

command "openvpn-dh-key" {
  exec = "openssl dHParam -outform PEM -out ${file.dh.path}"
  # also supplies stderr/stdout/stdin separately
}
```

**Comment by erikbor** [comment]
@ronaldtse 
By executing `command` in our examples the dh file would be created in on the Docker host itself and not inside the container. The variable path of `${file.dh.path}` would remain static, but we can't overwrite this file with that path on the host itself. So do we need to introduce an additional temporary `path`?

**Comment by ronaldtse** [comment]
@erikbor I meant that this entire configuration is to be passed inside the container, and therefore will be executed by Nereond inside the container.

**Comment by erikbor** [comment]
Hmm I see, I guess both approaches can have their place.
1. Having an option to do it outside of the container would result in not having to include openssl in the container itself.
2. Doing it inside the container keeps the host light weight.

**Comment by ronaldtse** [comment]
Good point, didn't think we were going into that now 😉 

Here it goes: https://github.com/riboseinc/riffol/issues/18

**Comment by drystone** [comment]
@ronaldtse @erikbor I think we should avoid anything run outside of the container that is not part of the static configuration because we won't necessarily have access to the host. A workaround would be to use Glyndol to generate dynamic configuration as we will have access to Glyndol's environment.

Also regarding `command`, I see that as a dependency and was considering having arbitrary scripts run as dependencies as well as package installations. The need for this has already arisen, to populate mysql in the riffol-wordpress example. The advantage of `command` is being able to specify the output filename(s) but I'm not sure whether it's a real benefit.

Which makes me think about environment variables. It would be useful for Riffol to be able to set environment variables for scripts (dependency and arbitrary healthcheck scripts are on my TODO) and for the applications themselves.

**Comment by ronaldtse** [comment]
* If Riffol runs on the host, we can just treat the Riffol context as a Riffol context (container or host)
* Agree that we should support environment variables for scripts.

Maybe we should define the "Riffol context" and what we can do with it?
