### ISSUE TITLE
systemd compatibility: hierarchical dependencies

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/riffol#20]
Allow specifying hierarchical dependencies just like systemd.

```
Wants=network-online.target
After=blah.target
```

**Comment by drystone** [comment]
I've been wondering about this. Mainly from the perspective of parallel spawning which is one good reason `systemd` was adopted. To keep things simple I'm wondering whether we could adopt a syntax like
```
init "name" {
    applications = [
        "application.app1"
        "=application.app2"
        "=application.app3"
        "=applicationgroup.group1"
        application.app4
        "=application.app5`
        "=applicationgroup.group2`
    ]
}
```
where we wait for `app1` to start before spawning all those with `=` concurrently (which includes all those in `group1` containing a list with similar syntax. We wait for all those (`app2`, `app3`, `group1`) to start before spawning `app4`, and then `app5` and `group2` when `app4` is started.
