### ISSUE TITLE
Allow setting environment variables

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/riffol#21]
I suppose we can do:

```
application "blah" {

  env {
    ES_HOME  = /usr/share/elasticsearch
    CONF_DIR = /etc/elasticsearch
    DATA_DIR = /var/lib/elasticsearch
    LOG_DIR  = /var/log/elasticsearch
    PID_DIR  = /var/run/elasticsearch
  }

  env_file = "blah.env"
}

```

**Comment by drystone** [comment]
Yes, needs to happen.

There may be existing mechanisms for `env_file`. UCL should support `.include`s, though I haven't tried. Something like `.include(key = env) "blah.env"` or perhaps `env = .include "blah.env"`

Also, I implemented an `@filename` syntax to include files in the NOC (this was just to expand CLI args though I think should-already/could-be-made to work
```
env = @blah.env
```
Though explicit `env_file` could be semantically clearer.

**Comment by drystone** [comment]
@ronaldtse I seem to remember you saying `systemd` cleared the environment before starting processes. I don't think this is a bad policy except it prevents. `docker run -e NEREOND_CONFIGSET=...`. A middle ground might be to have 
```
env {
    NEREOND_CONFIGSET=$NEREOND_CONFIGSET
}
```
so we can clean env for processes except those that are explicitly "forwarded" or "set"
