### ISSUE TITLE
Riffol’s symbol, logo, mascot

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/riffol#34]
* To represent Riffol on its Ribose Open Project site, a logo would be nice to have.
* The part of logo that requires creative effort is symbol. The symbol should be in vector format, square. Expect it to be shown on the open project site in sizes from around 30x30 to around 60x60px (roughly 0.3 to 0.6 inch real world).
* Strategically a project mascot is good to have as it makes it more straightforward to later create representations and variations for other circumstances, preserving conceptual consistency regardless of visual style.
* Salmon, roe, riffle, rust are the keywords (no need to represent all at once).

**Comment by strogonoff** [comment]
@drystone, @ronaldtse unless an icon already exists or Ricardo is currently actively working on one, I’d like to take care of this and source one from a friendly artist—is that OK?

**Comment by strogonoff** [comment]
haha just realized I can’t assign an issue to myself on this project 😅

**Comment by drystone** [comment]
@strogonoff sounds good to me :-) Spawn and stream are also good words ...

**Comment by ronaldtse** [comment]
@strogonoff Ricardo hasn't started working on it, but sure feel free to propose a vector 😉

**Comment by strogonoff** [comment]
Got it, if there’s an arrangement with Ricardo about Riffol logo then we can leave my idea for another project that’ll become part of Ribose Open in future.

I’d note that unless we are positively 100% sure that one person can work on all logos for all projects forever, it would make sense to start enforcing heterogeneity across projects where it’s expected, and see how theme handles the diversity.

(How we might not want unexpected diversity in fonts is the opposite side of the same coin. Not sure if I am getting this thought across)

**Comment by strogonoff** [comment]
Switching riffol.com to this friendly salmon as the logo; you can find it under [`assets/symbol.svg`](https://github.com/riboseinc/riffol.com/blob/master/assets/symbol.svg) there. You can also replace that file (and also `_software/riffol/assets/symbol.svg` for software package) with another symbol if you want. Note that it should be in SVG (see theme docs about [SVG guidelines](https://github.com/riboseinc/jekyll-theme-open-project/blob/master/README.md#svg-guidelines) and other logo-related info).

![salmon-reshaped](https://user-images.githubusercontent.com/292959/43443169-4de69c86-94ca-11e8-8d6f-3c76f4d6dd9e.png)

**Comment by ronaldtse** [comment]
@strogonoff this looks good! Thanks!
