### ISSUE TITLE
Exits with no reason

### ISSUE THREAD

**Issue by shimunn** [riboseinc/riffol#45]
Hi,

I'm currently trying to get riffol running without any luck, I've tried the latest release from github, crates.io and compiled the latest version from git. But all of them exhibit the same behaviour, if I run the binary it exists straight away with no error message and exit code 0, specifying a config or not doesn't make a difference. I've tried on my machine(Fedora 29 64bit) and under docker(debian:latest).

**Comment by shimunn** [comment]
Was missing a `,` in my config also opened a PR to print those errors to stderr.

**Comment by ronaldtse** [comment]
@shimunn thank you for the report! Indeed it should display any parsing errors such as the missing `,`. Needs to be more robust...
